version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astros
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_astros
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
